version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c " python -m spacy download en_core_web_sm && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      
    ports:
      - "8000:8000"
  
