# Generated by Django 3.2.8 on 2024-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_diagram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='diagrams/'),
        ),
    ]
